name: CI

on: push
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - run: |
          echo "ENV_VAL=\"${{ secrets.ENV_VAL }}\"" > env.ci
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
